/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.neu.info5100.components;

import edu.neu.info5100.database.DB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author sidb
 */
public class AdminUsersCrud extends javax.swing.JPanel {

  /**
   * Creates new form AdminUsersCrud
   */
  public AdminUsersCrud() {
    initComponents();
    loadTable();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

  private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange
    // TODO add your handling code here:
  }//GEN-LAST:event_jTable1PropertyChange

  public void loadTable() {
    Connection conn = new DB().connection();

    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Name");
    model.addColumn("Mobile");
    model.addColumn("Age");
    model.addColumn("Username");
    model.addColumn("Gender");
    model.addColumn("Role");
    model.addColumn("Organization");
    model.addColumn("Enterprise");
    model.addColumn("Verified");

    try {
      PreparedStatement pstm = conn.prepareStatement(
        "SELECT name, mobile, age, username, gender, role,organization,enterprise,verified FROM userdetails"
      );
      //      System.out.println(pstm);
      ResultSet Rs = pstm.executeQuery();

      while (Rs.next()) {
        model.addRow(
          new Object[] {
            Rs.getString("name"),
            Rs.getString("mobile"),
            Rs.getString("age"),
            Rs.getString("username"),
            Rs.getString("gender"),
            Rs.getString("role"),
            Rs.getString("organization"),
            Rs.getString("enterprise"),
            Rs.getInt("verified"),
          }
        );
      }
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
    jTable1.setModel(model);

    model.addTableModelListener(
      new TableModelListener() {
        public void tableChanged(TableModelEvent e) {
          PreparedStatement pstm;

          if (e.getType() == TableModelEvent.UPDATE) {
            DefaultTableModel model = (DefaultTableModel) (
              (TableModel) (e.getSource())
            );
            int rr = e.getFirstRow();
            int col = e.getColumn();

            String newString = String.valueOf(
              model.getValueAt(
                jTable1.getSelectedRow(),
                jTable1.getSelectedColumn()
              )
            );
            String username = model.getValueAt(rr, 3).toString();

            if (col == 0) {
              try {
                pstm =
                  conn.prepareStatement(
                    "UPDATE userdetails SET name=? WHERE username='" +
                    username +
                    "'"
                  );

                pstm.setString(1, newString);
                //  pstm.executeUpdate();
                //                                                                                System.out.println(pstm);
                pstm.executeUpdate();
              } catch (SQLException ex) {
                Logger
                  .getLogger(AdminUsersCrud.class.getName())
                  .log(Level.SEVERE, null, ex);
              }
            }
            if (col == 1) {
              try {
                pstm =
                  conn.prepareStatement(
                    "UPDATE userdetails SET mobile=? WHERE  username='" +
                    username +
                    "'"
                  );
                pstm.setInt(1, Integer.parseInt(newString));
                pstm.executeUpdate();
              } catch (SQLException ex) {
                Logger
                  .getLogger(AdminUsersCrud.class.getName())
                  .log(Level.SEVERE, null, ex);
              }
            }
            if (col == 2) {
              try {
                pstm =
                  conn.prepareStatement(
                    "UPDATE userdetails SET age=? WHERE  username='" +
                    username +
                    "'"
                  );
                pstm.setInt(1, Integer.parseInt(newString));
                pstm.executeUpdate();
              } catch (SQLException ex) {
                Logger
                  .getLogger(AdminUsersCrud.class.getName())
                  .log(Level.SEVERE, null, ex);
              }
            }
            if (col == 4) {
              try {
                pstm =
                  conn.prepareStatement(
                    "UPDATE userdetails SET gender=? WHERE  username='" +
                    username +
                    "'"
                  );
                pstm.setString(1, newString);
                pstm.executeUpdate();
              } catch (SQLException ex) {
                Logger
                  .getLogger(AdminUsersCrud.class.getName())
                  .log(Level.SEVERE, null, ex);
              }
            }

            if (col == 5) {
              try {
                pstm =
                  conn.prepareStatement(
                    "UPDATE userdetails SET role=? WHERE  username='" +
                    username +
                    "'"
                  );
                pstm.setString(1, newString);
              } catch (SQLException ex) {
                Logger
                  .getLogger(AdminUsersCrud.class.getName())
                  .log(Level.SEVERE, null, ex);
              }
            }

            if (col == 6) {
              try {
                pstm =
                  conn.prepareStatement(
                    "UPDATE userdetails SET organization=? WHERE  username='" +
                    username +
                    "'"
                  );
                pstm.setString(1, newString);
                pstm.executeUpdate();
              } catch (SQLException ex) {
                Logger
                  .getLogger(AdminUsersCrud.class.getName())
                  .log(Level.SEVERE, null, ex);
              }
            }
            if (col == 7) {
              try {
                pstm =
                  conn.prepareStatement(
                    "UPDATE userdetails SET enterprise=? WHERE  username='" +
                    username +
                    "'"
                  );

                pstm.setString(1, newString);
                pstm.executeUpdate();
              } catch (SQLException ex) {
                Logger
                  .getLogger(AdminUsersCrud.class.getName())
                  .log(Level.SEVERE, null, ex);
              }
            }
          }
        }
      }
    );
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
