/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.neu.info5100.components;

import edu.neu.info5100.database.DB;
import edu.neu.info5100.driver.INFO5100Project;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author sidb
 */
public class CustomerCurrentBookingPage extends javax.swing.JPanel {

  /**
   * Creates new form CustomerCurrentBookingPage
   */
  public CustomerCurrentBookingPage() {
    initComponents();
    LoadCurrentTrip();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    jLabel1 = new javax.swing.JLabel();
    pickupLabel = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    DestinationLabel = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    StatusText = new javax.swing.JLabel();
    refreshButton = new javax.swing.JButton();
    rideID = new javax.swing.JLabel();
    rideIDVal = new javax.swing.JLabel();

    jLabel1.setFont(new java.awt.Font("YuKyokasho Yoko", 0, 18)); // NOI18N
    jLabel1.setText("Pickup");

    pickupLabel.setFont(new java.awt.Font("YuKyokasho Yoko", 1, 18)); // NOI18N
    pickupLabel.setText("PickUpLabel");

    jLabel3.setFont(new java.awt.Font("YuKyokasho Yoko", 0, 18)); // NOI18N
    jLabel3.setText("Destination");

    DestinationLabel.setFont(new java.awt.Font("YuKyokasho Yoko", 1, 18)); // NOI18N
    DestinationLabel.setText("DestinationLabel");

    jLabel2.setFont(new java.awt.Font("YuKyokasho Yoko", 0, 18)); // NOI18N
    jLabel2.setText("Status");

    StatusText.setFont(new java.awt.Font("YuKyokasho Yoko", 1, 18)); // NOI18N
    StatusText.setText("Status");

    refreshButton.setText("Refresh");
    refreshButton.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          refreshButtonActionPerformed(evt);
        }
      }
    );

    rideID.setFont(new java.awt.Font("YuKyokasho Yoko", 0, 18)); // NOI18N
    rideID.setText("RideID");

    rideIDVal.setFont(new java.awt.Font("YuKyokasho Yoko", 1, 18)); // NOI18N
    rideIDVal.setText("ID");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          layout
            .createSequentialGroup()
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
            .addComponent(
              refreshButton,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              138,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(123, 123, 123)
        )
        .addGroup(
          layout
            .createSequentialGroup()
            .addGap(169, 169, 169)
            .addGroup(
              layout
                .createParallelGroup(
                  javax.swing.GroupLayout.Alignment.LEADING,
                  false
                )
                .addComponent(
                  jLabel3,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
                .addComponent(jLabel2)
                .addComponent(
                  rideID,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
                .addComponent(
                  jLabel1,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  87,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
            )
            .addGap(26, 26, 26)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(StatusText)
                .addGroup(
                  layout
                    .createParallelGroup(
                      javax.swing.GroupLayout.Alignment.LEADING,
                      false
                    )
                    .addComponent(
                      pickupLabel,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      Short.MAX_VALUE
                    )
                    .addComponent(
                      DestinationLabel,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      Short.MAX_VALUE
                    )
                    .addComponent(
                      rideIDVal,
                      javax.swing.GroupLayout.Alignment.TRAILING,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      Short.MAX_VALUE
                    )
                )
            )
            .addContainerGap(133, Short.MAX_VALUE)
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addGap(49, 49, 49)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(
                  rideID,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  27,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(rideIDVal)
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(
                  jLabel1,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  27,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(pickupLabel)
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
            )
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(DestinationLabel)
            )
            .addGap(18, 18, 18)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(StatusText)
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.RELATED,
              102,
              Short.MAX_VALUE
            )
            .addComponent(
              refreshButton,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              41,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(72, 72, 72)
        )
    );
  } // </editor-fold>//GEN-END:initComponents

  private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
    // TODO add your handling code here:
    LoadCurrentTrip();
  }//GEN-LAST:event_refreshButtonActionPerformed

  private void LoadCurrentTrip() {
    Connection conn = new DB().connection();
    rideIDVal.setText("No Booking");
    pickupLabel.setText("No Booking");
    DestinationLabel.setText("No Booking");
    StatusText.setText("No Booking");
    try {
      PreparedStatement pstm = conn.prepareStatement(
        "SELECT b.fromLocation ,b.toLocation, b.rideid, c.status  from bookings b INNER JOIN cabrides c ON b.rideid = c.id WHERE b.customerusername=? and c.status='InProgress';"
      );
      pstm.setString(1,INFO5100Project.getSession().GetUsername());
      ResultSet rs = pstm.executeQuery();
      while (rs.next()) {
        rideIDVal.setText(rs.getString("rideid"));
        pickupLabel.setText(rs.getString("fromLocation"));
        DestinationLabel.setText(rs.getString("toLocation"));
        StatusText.setText(rs.getString("status"));
        //                DefaultComboBoxModel model = (DefaultComboBoxModel)comboBox1.getModel();

      }
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel DestinationLabel;
  private javax.swing.JLabel StatusText;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel pickupLabel;
  private javax.swing.JButton refreshButton;
  private javax.swing.JLabel rideID;
  private javax.swing.JLabel rideIDVal;
  // End of variables declaration//GEN-END:variables
}