/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.neu.info5100.components;

import edu.neu.info5100.database.DB;
import edu.neu.info5100.driver.INFO5100Project;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author megha
 */
public class DriverUpdateEnterpriseInformation extends javax.swing.JPanel {
    String filename=null;
    byte[] license=null;
    String s;
    
    /**
     * Creates new form DriverUpdateEnterpriseInformation
     */
    public DriverUpdateEnterpriseInformation() {
        initComponents();
        loadEnterprise();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Enterprisecombo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        LicenseUpload = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("Enterprise Information");

        Enterprisecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Enterprisecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterprisecomboActionPerformed(evt);
            }
        });

        jButton1.setText("Upload License");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        LicenseUpload.setPreferredSize(new java.awt.Dimension(200, 200));

        jButton2.setText("Save Changes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jButton1))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LicenseUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Enterprisecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jButton2)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Enterprisecombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(LicenseUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
public ImageIcon ResizeImage(String imgPath){ ImageIcon MyImage = new ImageIcon(imgPath);
Image img = MyImage.getImage();
Image newImage = img.getScaledInstance(LicenseUpload.getWidth(), LicenseUpload.getHeight(),Image.SCALE_SMOOTH); 
ImageIcon image = new ImageIcon(newImage);
return image; }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        FileNameExtensionFilter filter=new FileNameExtensionFilter("*.IMAGE","jpg","gif","png");
        chooser.addChoosableFileFilter(filter);
        int result=chooser.showSaveDialog(null);
        if(result== JFileChooser.APPROVE_OPTION){
            File selectedFile=chooser.getSelectedFile();
            String path=selectedFile.getAbsolutePath();
            LicenseUpload.setIcon(ResizeImage(path));
            s=path;
           
        } 
        else if(result== JFileChooser.CANCEL_OPTION){
            System.out.println("No dATA");


//        chooser.showOpenDialog(null);
//        File f = chooser.getSelectedFile();
//        filename = f.getAbsolutePath();
//        ImageIcon imageIcon= new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(LicenseUpload.getWidth(),LicenseUpload.getHeight(),Image.SCALE_SMOOTH));
//        LicenseUpload.setIcon(imageIcon);
//        try{
//            File image=new File(filename);
//            FileInputStream fis= new FileInputStream(image);
//            ByteArrayOutputStream bos=new ByteArrayOutputStream();
//            byte[] buff=new byte[1024];
//            for(int readNum;(readNum=fis.read(buff))!=-1;){
//                bos.write(buff,0,readNum);
//            }
//            license=bos.toByteArray();
//            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         
           
    try {
        Connection conn = new DB().connection();
      PreparedStatement pstm = conn.prepareStatement(
        "Update userdetails set license=? where username=?;"
      );
      InputStream is = new FileInputStream(new File(s));
       pstm.setBlob(1,is);
        pstm.setString(
          2,
          String.valueOf(INFO5100Project.getSession().GetUsername()));
        
      pstm.executeUpdate();
      JOptionPane.showMessageDialog(null, "Your details have been saved!");
      
    } catch (Exception e) {
      e.printStackTrace();
      System.out.println("h");
    }
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void EnterprisecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterprisecomboActionPerformed

     Connection conn = new DB().connection();
     String selectedEnterprise = (String) Enterprisecombo.getSelectedItem();
    


    try {
      PreparedStatement pstm = conn.prepareStatement(
        "UPDATE userdetails set enterprise=? where username=?"
      );
      pstm.setString(
        1,String.valueOf(selectedEnterprise)
        
      );     
       pstm.setString(
        2,String.valueOf(INFO5100Project.getSession().GetUsername())
        
      );    
        pstm.executeUpdate();
        
      
      
    } catch (Exception e) {
      System.out.println(e);
      JOptionPane.showMessageDialog(null,"Please try again!");
    }
    }//GEN-LAST:event_EnterprisecomboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Enterprisecombo;
    private javax.swing.JLabel LicenseUpload;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void loadEnterprise() {
        Enterprisecombo.removeAllItems();

        //String usernameSupport=String.valueOf(INFO5100Project.getSession().GetUsername());
        Connection conn = new DB().connection();
    try {

      PreparedStatement pstm = conn.prepareStatement(
        "SELECT name FROM enterprise;"
      );
      
            System.out.println(pstm);

      ResultSet rs = pstm.executeQuery();
    
      while (rs.next()) {
          Enterprisecombo.addItem((rs.getString("name")));
          

      }
    } catch (Exception e) {
      System.out.println("null");
    }
 
    }
    }

