/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.neu.info5100.components;

import edu.neu.info5100.database.DB;
import edu.neu.info5100.driver.INFO5100Project;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author megha
 */
public class DriverViewLicense extends javax.swing.JPanel {

    /**
     * Creates new form DriverViewLicense
     */
    public DriverViewLicense() {
        initComponents();
        LoadPhoto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        viewLic = new javax.swing.JLabel();

        jLabel1.setText("My License");

        viewLic.setMaximumSize(new java.awt.Dimension(200, 200));
        viewLic.setMinimumSize(new java.awt.Dimension(200, 200));
        viewLic.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(viewLic, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addComponent(viewLic, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel viewLic;
    // End of variables declaration//GEN-END:variables

    private void LoadPhoto() {
          Connection conn = new DB().connection();
           
    try {
      PreparedStatement pstm = conn.prepareStatement(
        "Select license from userdetails where username=?;"
      );
        pstm.setString(
          1,
          String.valueOf(INFO5100Project.getSession().GetUsername()));
        
      ResultSet rs = pstm.executeQuery();
      if(rs.next()){
          byte[] license_image=rs.getBytes("license");
           ImageIcon imageIcon= new ImageIcon(license_image);
           Image lic=imageIcon.getImage();
           Image driverlicense=lic.getScaledInstance(400,400,Image.SCALE_SMOOTH);
           ImageIcon newlicense=new ImageIcon(driverlicense);
           viewLic.setIcon(newlicense);
           
      }
        
       
       
      
    } catch (Exception e) {
      e.printStackTrace();
    }
    
    }
}
