/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.neu.info5100.components;

import edu.neu.info5100.database.DB;
import edu.neu.info5100.driver.INFO5100Project;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sidb
 */
public class DriverLeftPane extends javax.swing.JPanel {

  /**
   * Creates new form DriverLeftPane
   */
  public DriverLeftPane() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateRide = new javax.swing.JButton();
        CurrentRide = new javax.swing.JButton();
        RideHistory = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        CreateRide.setText("Create Ride");
        CreateRide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateRideActionPerformed(evt);
            }
        });

        CurrentRide.setText("Current Ride");
        CurrentRide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrentRideActionPerformed(evt);
            }
        });

        RideHistory.setText("Ride History");
        RideHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RideHistoryActionPerformed(evt);
            }
        });

        jButton1.setText("Logout");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update Enterprise Information");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("View License");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Update Enterprise Information");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("View License");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Scheduled Rides");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(RideHistory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CurrentRide, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CreateRide, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CreateRide)
                .addGap(9, 9, 9)
                .addComponent(CurrentRide)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addGap(9, 9, 9)
                .addComponent(RideHistory)
                .addGap(198, 198, 198)
                .addComponent(jButton1)
                .addContainerGap(161, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

  private void CurrentRideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentRideActionPerformed
    // TODO add your handling code here:DriverCurrentTripPage
    Connection conn = new DB().connection();


    try {
      PreparedStatement pstm = conn.prepareStatement(
        "Select enterprise, license  FROM userdetails where username=?;"
      );
      pstm.setString(1,INFO5100Project.getSession().GetUsername());
     ResultSet Rs = pstm.executeQuery();
      while (Rs.next()) {
        if(Rs.getString("enterprise")==null ||  Rs.getBlob("license")==null){
            JOptionPane.showMessageDialog(null, "Please enter basic driver details such as enterprise information and lciense to continue!");
        }
           
        else{
            INFO5100Project
      .getUI()
      .ChangeRightPanel(new DriverCurrentTripPage(), "DriverCurrentTripPage");
        }
          
    
      }
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }//GEN-LAST:event_CurrentRideActionPerformed

  private void RideHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RideHistoryActionPerformed
    // TODO add your handling code here:
    Connection conn = new DB().connection();


    try {
      PreparedStatement pstm = conn.prepareStatement(
        "Select enterprise, license  FROM userdetails where username=?;"
      );
      pstm.setString(1,INFO5100Project.getSession().GetUsername());
     ResultSet Rs = pstm.executeQuery();
      while (Rs.next()) {
        if(Rs.getString("enterprise")==null ||  Rs.getBlob("license")==null){
            JOptionPane.showMessageDialog(null, "Please enter basic driver details such as enterprise information and lciense to continue!");
        }
           
        else{
            INFO5100Project
      .getUI()
      .ChangeRightPanel(new DriverRideHistory(), "DriverRideHistory");
          
    
      }
    } }catch (Exception e) {
      System.out.println(e.getMessage());
    }
    
    
  }//GEN-LAST:event_RideHistoryActionPerformed

  private void CreateRideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateRideActionPerformed
    // TODO add your handling code here:
    
    Connection conn = new DB().connection();


    try {
      PreparedStatement pstm = conn.prepareStatement(
        "Select enterprise, license  FROM userdetails where username=?;"
      );
      pstm.setString(1,INFO5100Project.getSession().GetUsername());
     ResultSet Rs = pstm.executeQuery();
      while (Rs.next()) {
        if(Rs.getString("enterprise")==null ||  Rs.getBlob("license")==null){
            JOptionPane.showMessageDialog(null, "Please enter basic driver details such as enterprise information and lciense to continue!");
        }
           
        else{
            INFO5100Project
      .getUI()
      .ChangeRightPanel(new DriverCreateRide(), "DriverCreateRide");
        }
          
    
      }
    } catch (Exception e) {
      System.out.println(e.getMessage());
      
    }

   // if(INFO5100Project.getSession().getUsername())
    
  }//GEN-LAST:event_CreateRideActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        INFO5100Project.getUI().ChangeLeftPanel(new LoginSignupPane(), "LoginSignupPane");
        INFO5100Project.getUI().ChangeRightPanel(new LoginPage(), "LoginPage");
        INFO5100Project.getSession().DeleteSession();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        INFO5100Project
      .getUI()
      .ChangeRightPanel(new DriverUpdateEnterpriseInformation(), "DriverUpdateEnterpriseInformation");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         INFO5100Project
      .getUI()
      .ChangeRightPanel(new DriverViewLicense(), "DriverViewLicense");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        INFO5100Project.getUI().ChangeLeftPanel(new LoginSignupPane(), "LoginSignUp");
        INFO5100Project.getUI().ChangeRightPanel(new LoginPage(), "LoginPage");
        INFO5100Project.getSession().DeleteSession();
    }//GEN-LAST:event_jButton1ActionPerformed
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        INFO5100Project
      .getUI()
      .ChangeRightPanel(new ScheduledRides(), "ScheduledRides");
        
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateRide;
    private javax.swing.JButton CurrentRide;
    private javax.swing.JButton RideHistory;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}