/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.neu.info5100.components;

import edu.neu.info5100.database.DB;
import edu.neu.info5100.driver.INFO5100Project;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author sidb
 */
public class OrgAddMembers extends javax.swing.JPanel {

    /**
     * Creates new form OrgAddMembers
     */
    public OrgAddMembers() {
        initComponents();
         LoadEnterpriseDropdown();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        orgNameVal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addOrgButton = new javax.swing.JButton();
        EnterpriseDropdown = new javax.swing.JComboBox<>();

        jLabel1.setText("Name");

        jLabel2.setText("Enterprise");

        addOrgButton.setText("Add Org");
        addOrgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrgButtonActionPerformed(evt);
            }
        });

        EnterpriseDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(orgNameVal)
                        .addGap(149, 149, 149))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addOrgButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EnterpriseDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(132, 132, 132))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(orgNameVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(EnterpriseDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(addOrgButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private boolean CheckIfExists(){
              Connection conn = new DB().connection();
              int doc = 0;
               try {

      PreparedStatement pstm = conn.prepareStatement(
        "SELECT COUNT(*) as count FROM organization Where name = ?"
      );
      
      pstm.setString(1, orgNameVal.getText());
      ResultSet rs = pstm.executeQuery();
      while (rs.next()) {
         doc = rs.getInt("count");
        //                DefaultComboBoxModel model = (DefaultComboBoxModel)comboBox1.getModel();
        if(doc==1){
            return true;
        }
      }
    } catch (Exception e) {
      System.out.println(e);
    }

              
              return false;
    }
    private void addOrgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrgButtonActionPerformed
        // TODO add your handling code here:
        
      if(CheckIfExists()){
           JOptionPane.showMessageDialog(
          null,
          "Org Already Exists"
        );
      }else{
           Connection conn = new DB().connection();
      
{
          
     
      try {
        PreparedStatement pstm = conn.prepareStatement(
          "INSERT INTO organization (name ,enterprise_id) VALUES(?, ?);"
        );
        pstm.setString(
          1,
          orgNameVal.getText()
        );
        
      pstm.setInt(2, GetEnterpriseID());
//);

        System.out.println(pstm);
        pstm.executeUpdate();

        //                }
        JOptionPane.showMessageDialog(
          null,
          "Org Creation Successfull"
        );
      } catch (Exception e3) {
        System.out.println("null");
      }
       }
    
      }
     
    }//GEN-LAST:event_addOrgButtonActionPerformed

    private int GetEnterpriseID() {
        int doc =0;
    Connection conn = new DB().connection();
    try {

      PreparedStatement pstm = conn.prepareStatement(
        "SELECT id FROM enterprise Where name = ?"
      );
      
      pstm.setString(1, String.valueOf(EnterpriseDropdown.getSelectedItem()));
      ResultSet rs = pstm.executeQuery();
      while (rs.next()) {
         doc = rs.getInt("id");
        //                DefaultComboBoxModel model = (DefaultComboBoxModel)comboBox1.getModel();
        return doc;
      }
    } catch (Exception e) {
      System.out.println(e);
    }
    return doc;
  }
      private void LoadEnterpriseDropdown() {
    Connection conn = new DB().connection();
    try {
      EnterpriseDropdown.removeAllItems();

      PreparedStatement pstm = conn.prepareStatement(
        "SELECT Distinct name FROM enterprise"
      );
      ResultSet rs = pstm.executeQuery();
      while (rs.next()) {
        String doc = rs.getString("name");
        //                DefaultComboBoxModel model = (DefaultComboBoxModel)comboBox1.getModel();

        EnterpriseDropdown.addItem(doc);
      }
    } catch (Exception e) {
      System.out.println("null");
    }
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> EnterpriseDropdown;
    private javax.swing.JButton addOrgButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField orgNameVal;
    // End of variables declaration//GEN-END:variables
}
