/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.neu.info5100.components;

import edu.neu.info5100.database.DB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author sidb
 */
public class Reporting extends javax.swing.JPanel {

  /**
   * Creates new form Reporting
   */
  public Reporting() {
    initComponents();
    LoadData();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    CutomersVal = new javax.swing.JLabel();
    RidesVal = new javax.swing.JLabel();
    DriversVal = new javax.swing.JLabel();
    OrgVal = new javax.swing.JLabel();
    EnterpriseVal = new javax.swing.JLabel();

    jLabel1.setText("Total Organisation");

    jLabel2.setText("Total Customers");

    jLabel3.setText("Total Rides");

    jLabel4.setText("Total Drivers");

    jLabel5.setText("Total Enterprises");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addGap(94, 94, 94)
            .addGroup(
              layout
                .createParallelGroup(
                  javax.swing.GroupLayout.Alignment.LEADING,
                  false
                )
                .addComponent(
                  jLabel2,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
                .addComponent(
                  jLabel1,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
                .addComponent(
                  jLabel3,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
                .addComponent(
                  jLabel4,
                  javax.swing.GroupLayout.Alignment.TRAILING,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
                .addComponent(
                  jLabel5,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
            )
            .addGap(18, 18, 18)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(CutomersVal)
                .addComponent(RidesVal)
                .addComponent(DriversVal)
                .addComponent(OrgVal)
                .addComponent(EnterpriseVal)
            )
            .addContainerGap(292, Short.MAX_VALUE)
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addGap(96, 96, 96)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(CutomersVal)
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
            )
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(RidesVal)
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
            )
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(DriversVal)
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
            )
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(OrgVal)
            )
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
            )
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(EnterpriseVal)
            )
            .addContainerGap(171, Short.MAX_VALUE)
        )
    );
  } // </editor-fold>//GEN-END:initComponents

  public void LoadData() {
    Connection conn = new DB().connection();

    // Total Users -  SELECT COUNT(*) as Count from userdetails u ;
    //Total Cab Rides - SELECT COUNT(*) as Count from cabrides c ;
    //Total Drivers - SELECT COUNT(*) as Count from userdetails u WHERE role='driver'
    //Total Organisations - SELECT COUNT(*) as Count from organization o ;
    //Total Enterprises - SELECT COUNT(*) as Count from enterprise e ;
    try {
      PreparedStatement pstm = conn.prepareStatement(
        "SELECT COUNT(*) as Count from userdetails u"
      );
      //      System.out.println(pstm);
      ResultSet Rs = pstm.executeQuery();

      while (Rs.next()) {
        CutomersVal.setText(Rs.getString("count"));
      }
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
    try {
      PreparedStatement pstm = conn.prepareStatement(
        " SELECT COUNT(*) as Count from cabrides c"
      );
      //      System.out.println(pstm);
      ResultSet Rs = pstm.executeQuery();

      while (Rs.next()) {
        RidesVal.setText(Rs.getString("count"));
      }
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
    try {
      PreparedStatement pstm = conn.prepareStatement(
        " SELECT COUNT(*) as Count from userdetails u WHERE role='driver'"
      );
      //      System.out.println(pstm);
      ResultSet Rs = pstm.executeQuery();

      while (Rs.next()) {
        DriversVal.setText(Rs.getString("count"));
      }
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
    try {
      PreparedStatement pstm = conn.prepareStatement(
        " SELECT COUNT(*) as Count from enterprise e"
      );
      //      System.out.println(pstm);
      ResultSet Rs = pstm.executeQuery();

      while (Rs.next()) {
        EnterpriseVal.setText(Rs.getString("count"));
      }
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
    try {
      PreparedStatement pstm = conn.prepareStatement(
        "SELECT COUNT(*) as Count from organization o"
      );
      //      System.out.println(pstm);
      ResultSet Rs = pstm.executeQuery();

      while (Rs.next()) {
        OrgVal.setText(Rs.getString("count"));
      }
    } catch (Exception e) {
      System.out.println(e.getMessage());
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel CutomersVal;
  private javax.swing.JLabel DriversVal;
  private javax.swing.JLabel EnterpriseVal;
  private javax.swing.JLabel OrgVal;
  private javax.swing.JLabel RidesVal;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  // End of variables declaration//GEN-END:variables
}
