/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.neu.info5100.ui;

import com.formdev.flatlaf.FlatDarculaLaf;
import edu.neu.info5100.components.LoginSignupPane;
import edu.neu.info5100.driver.INFO5100Project;
import java.awt.Container;
import javax.swing.UIManager;

/**
 *
 * @author sidb
 */
public class UI extends javax.swing.JFrame {

  Container contentPanel;

  /**
   * Creates new form UI
   */
  public UI() {
      try {
   UIManager.setLookAndFeel( new FlatDarculaLaf() );
 } catch( Exception ex ) {
     System.err.println( "Failed to initialize LaF" );
 }
    initComponents();
    contentPanel = getContentPane();
    leftPane.add(new LoginSignupPane(), "LoginPage");
    leftPane.validate();
    leftPane.revalidate();


  }
  

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPane = new javax.swing.JPanel();
        rightPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftPane.setLayout(new java.awt.CardLayout());

        rightPane.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPane, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rightPane, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftPane, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
            .addComponent(rightPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  public void ChangeRightPanel(javax.swing.JPanel j, String name) {
    rightPane.removeAll();
    rightPane.add(j, name);
    rightPane.validate();
    rightPane.revalidate();

    System.out.println("Right Pane changed to" + name); //for debugging purposes
    validate();
    setVisible(true);
  }

  public void ChangeLeftPanel(javax.swing.JPanel j, String name) {
    leftPane.removeAll();
    leftPane.add(j, name);
    leftPane.validate();
    leftPane.revalidate();

    System.out.println("Left Pane changed to " + name); //for debugging purposes
    validate();
    setVisible(true);
  }

  /**
   * @param args the command line arguments
   */
//   public static void UI(String args[]) {
//     /* Set the Nimbus look and feel */
//     //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//     /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//      * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//      */
//     try {
//       for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//         if ("Nimbus".equals(info.getName())) {
//           javax.swing.UIManager.setLookAndFeel(info.getClassName());
//           break;
//         }
//       }
//     } catch (ClassNotFoundException ex) {
//       java.util.logging.Logger
//         .getLogger(UI.class.getName())
//         .log(java.util.logging.Level.SEVERE, null, ex);
//     } catch (InstantiationException ex) {
//       java.util.logging.Logger
//         .getLogger(UI.class.getName())
//         .log(java.util.logging.Level.SEVERE, null, ex);
//     } catch (IllegalAccessException ex) {
//       java.util.logging.Logger
//         .getLogger(UI.class.getName())
//         .log(java.util.logging.Level.SEVERE, null, ex);
//     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//       java.util.logging.Logger
//         .getLogger(UI.class.getName())
//         .log(java.util.logging.Level.SEVERE, null, ex);
//     }
//     //</editor-fold>

//     /* Create and display the form */
//     java.awt.EventQueue.invokeLater(
//       new Runnable() {
//         public void run() {
//           new UI().setVisible(true);
//         }
//       }
//     );
//   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel leftPane;
    private javax.swing.JPanel rightPane;
    // End of variables declaration//GEN-END:variables
}
